import type { TSLNodeEditorGraph, TSLNodeEditorPreset } from './TSLNodeEditor'

type PresetNode = TSLNodeEditorGraph['nodes'][number]
type PresetConnection = TSLNodeEditorGraph['connections'][number]

const node = (
  id: string,
  type: string,
  label: string,
  x: number,
  y: number,
  inputs: string[],
  outputs: string[],
  extra: Partial<PresetNode> = {},
): PresetNode => ({
  id,
  type,
  label,
  x,
  y,
  inputs,
  outputs,
  ...extra,
})

const numberNode = (
  id: string,
  x: number,
  y: number,
  value: string,
  extra: Partial<PresetNode> = {},
): PresetNode =>
  node(id, 'number', 'Number', x, y, [], ['value'], {
    value,
    slider: false,
    updateMode: 'manual',
    updateSource: 'value',
    ...extra,
  })

const colorNode = (id: string, x: number, y: number, value: string): PresetNode =>
  node(id, 'color', 'Color', x, y, [], ['color'], { value })

const conn = (
  id: string,
  fromNodeId: string,
  fromPin: string,
  toNodeId: string,
  toPin: string,
): PresetConnection => ({
  id,
  from: { nodeId: fromNodeId, pin: fromPin },
  to: { nodeId: toNodeId, pin: toPin },
})

const APPLE_GLASS_GRAPH: TSLNodeEditorGraph = {
  nodes: [
    node('glass-geometry', 'geometryPrimitive', 'Geometry', 60, 80, [], ['geometry'], {
      value: 'plane',
    }),
    node('glass-geometry-output', 'geometryOutput', 'Geometry Output', 320, 80, ['geometry'], []),
    node('glass-uv', 'uv', 'UV', 60, 260, [], ['value']),
    node('glass-screen-uv', 'screenUV', 'Screen UV', 60, 420, [], ['value']),
    node('glass-ramp-vertical', 'mxRampTB', 'MX Ramp TB', 1340, 260, ['a', 'b', 'coord'], ['value']),
    node('glass-ramp-horizontal', 'mxRampLR', 'MX Ramp LR', 1340, 540, ['a', 'b', 'coord'], ['value']),
    node('glass-tint-mix', 'mix', 'Mix', 1600, 400, ['a', 'b', 't'], ['value']),
    node('glass-uv-split', 'splitVec2', 'Split Vec2', 320, 260, ['value'], ['x', 'y']),
    node('glass-top-highlight', 'smoothstep', 'Smoothstep', 840, 260, ['edge0', 'edge1', 'x'], ['value']),
    node('glass-highlight-mix', 'mix', 'Mix', 1860, 260, ['a', 'b', 't'], ['value']),
    node('glass-normal-view', 'normalView', 'Normal View', 60, 600, [], ['value']),
    node('glass-normal-split', 'splitVec3', 'Split Vec3', 320, 600, ['value'], ['x', 'y', 'z']),
    node('glass-normal-abs', 'abs', 'Abs', 580, 600, ['value'], ['value']),
    node('glass-normal-invert', 'oneMinus', 'OneMinus', 840, 600, ['value'], ['value']),
    node('glass-rim-mask', 'smoothstep', 'Smoothstep', 1100, 600, ['edge0', 'edge1', 'x'], ['value']),
    node('glass-edge-mix', 'mix', 'Mix', 2120, 420, ['a', 'b', 't'], ['value']),
    node('glass-glow-mask', 'max', 'Max', 1340, 760, ['a', 'b'], ['value']),
    node('glass-emissive-mult', 'multiply', 'Multiply', 1600, 760, ['a', 'b'], ['value']),
    node('glass-opacity-mix', 'mix', 'Mix', 1600, 980, ['a', 'b', 't'], ['value']),
    node(
      'glass-material',
      'physicalMaterial',
      'PhysicalMaterial',
      2380,
      520,
      [
        'baseColor',
        'baseColorTexture',
        'roughness',
        'roughnessMap',
        'metalness',
        'metalnessMap',
        'emissive',
        'emissiveMap',
        'emissiveIntensity',
        'normalMap',
        'normalScale',
        'clearcoat',
        'clearcoatRoughness',
        'clearcoatNormal',
        'aoMap',
        'aoMapIntensity',
        'envMap',
        'envMapIntensity',
        'opacity',
        'alphaTest',
        'alphaHash',
      ],
      ['baseColor', 'roughness', 'metalness'],
    ),
    node('glass-output', 'output', 'Fragment Output', 2680, 520, ['baseColor', 'roughness', 'metalness'], []),

    colorNode('glass-bottom-color', 1080, 160, '#d9e7ff'),
    colorNode('glass-top-color', 1080, 280, '#ffffff'),
    colorNode('glass-left-color', 1080, 460, '#d7f5ff'),
    colorNode('glass-right-color', 1080, 620, '#f3e7ff'),
    colorNode('glass-highlight-color', 1860, 120, '#ffffff'),
    colorNode('glass-edge-color', 2120, 560, '#c9f1ff'),
    colorNode('glass-emissive-color', 1600, 620, '#eefbff'),

    numberNode('glass-tint-balance', 1600, 560, '0.38'),
    numberNode('glass-top-low', 580, 120, '0.58'),
    numberNode('glass-top-high', 580, 260, '0.96'),
    numberNode('glass-rim-low', 840, 460, '0.18'),
    numberNode('glass-rim-high', 840, 760, '0.82'),
    numberNode('glass-roughness', 2120, 840, '0.12'),
    numberNode('glass-metalness', 2120, 980, '0.0'),
    numberNode('glass-emissive-intensity', 1860, 900, '0.28'),
    numberNode('glass-clearcoat', 2120, 1120, '1.0'),
    numberNode('glass-clearcoat-roughness', 2120, 1260, '0.04'),
    numberNode('glass-opacity-min', 1340, 900, '0.16'),
    numberNode('glass-opacity-max', 1340, 1040, '0.32'),
    numberNode('glass-alpha-test', 2380, 980, '0.02'),
  ],
  connections: [
    conn('glass-geometry-link', 'glass-geometry', 'geometry', 'glass-geometry-output', 'geometry'),
    conn('glass-vertical-ramp-coord', 'glass-uv', 'value', 'glass-ramp-vertical', 'coord'),
    conn('glass-vertical-ramp-a', 'glass-bottom-color', 'color', 'glass-ramp-vertical', 'a'),
    conn('glass-vertical-ramp-b', 'glass-top-color', 'color', 'glass-ramp-vertical', 'b'),
    conn('glass-horizontal-ramp-coord', 'glass-screen-uv', 'value', 'glass-ramp-horizontal', 'coord'),
    conn('glass-horizontal-ramp-a', 'glass-left-color', 'color', 'glass-ramp-horizontal', 'a'),
    conn('glass-horizontal-ramp-b', 'glass-right-color', 'color', 'glass-ramp-horizontal', 'b'),
    conn('glass-tint-mix-a', 'glass-ramp-vertical', 'value', 'glass-tint-mix', 'a'),
    conn('glass-tint-mix-b', 'glass-ramp-horizontal', 'value', 'glass-tint-mix', 'b'),
    conn('glass-tint-mix-t', 'glass-tint-balance', 'value', 'glass-tint-mix', 't'),

    conn('glass-uv-split-link', 'glass-uv', 'value', 'glass-uv-split', 'value'),
    conn('glass-top-low-link', 'glass-top-low', 'value', 'glass-top-highlight', 'edge0'),
    conn('glass-top-high-link', 'glass-top-high', 'value', 'glass-top-highlight', 'edge1'),
    conn('glass-top-mask-link', 'glass-uv-split', 'y', 'glass-top-highlight', 'x'),
    conn('glass-highlight-a', 'glass-tint-mix', 'value', 'glass-highlight-mix', 'a'),
    conn('glass-highlight-b', 'glass-highlight-color', 'color', 'glass-highlight-mix', 'b'),
    conn('glass-highlight-t', 'glass-top-highlight', 'value', 'glass-highlight-mix', 't'),

    conn('glass-normal-split-link', 'glass-normal-view', 'value', 'glass-normal-split', 'value'),
    conn('glass-normal-abs-link', 'glass-normal-split', 'z', 'glass-normal-abs', 'value'),
    conn('glass-normal-invert-link', 'glass-normal-abs', 'value', 'glass-normal-invert', 'value'),
    conn('glass-rim-low-link', 'glass-rim-low', 'value', 'glass-rim-mask', 'edge0'),
    conn('glass-rim-high-link', 'glass-rim-high', 'value', 'glass-rim-mask', 'edge1'),
    conn('glass-rim-mask-link', 'glass-normal-invert', 'value', 'glass-rim-mask', 'x'),

    conn('glass-edge-mix-a', 'glass-highlight-mix', 'value', 'glass-edge-mix', 'a'),
    conn('glass-edge-mix-b', 'glass-edge-color', 'color', 'glass-edge-mix', 'b'),
    conn('glass-edge-mix-t', 'glass-rim-mask', 'value', 'glass-edge-mix', 't'),

    conn('glass-glow-mask-a', 'glass-top-highlight', 'value', 'glass-glow-mask', 'a'),
    conn('glass-glow-mask-b', 'glass-rim-mask', 'value', 'glass-glow-mask', 'b'),
    conn('glass-emissive-a', 'glass-emissive-color', 'color', 'glass-emissive-mult', 'a'),
    conn('glass-emissive-b', 'glass-glow-mask', 'value', 'glass-emissive-mult', 'b'),

    conn('glass-opacity-min-link', 'glass-opacity-min', 'value', 'glass-opacity-mix', 'a'),
    conn('glass-opacity-max-link', 'glass-opacity-max', 'value', 'glass-opacity-mix', 'b'),
    conn('glass-opacity-mask-link', 'glass-rim-mask', 'value', 'glass-opacity-mix', 't'),

    conn('glass-material-base', 'glass-edge-mix', 'value', 'glass-material', 'baseColor'),
    conn('glass-material-roughness', 'glass-roughness', 'value', 'glass-material', 'roughness'),
    conn('glass-material-metalness', 'glass-metalness', 'value', 'glass-material', 'metalness'),
    conn('glass-material-emissive', 'glass-emissive-mult', 'value', 'glass-material', 'emissive'),
    conn(
      'glass-material-emissive-intensity',
      'glass-emissive-intensity',
      'value',
      'glass-material',
      'emissiveIntensity',
    ),
    conn('glass-material-clearcoat', 'glass-clearcoat', 'value', 'glass-material', 'clearcoat'),
    conn(
      'glass-material-clearcoat-roughness',
      'glass-clearcoat-roughness',
      'value',
      'glass-material',
      'clearcoatRoughness',
    ),
    conn('glass-material-opacity', 'glass-opacity-mix', 'value', 'glass-material', 'opacity'),
    conn('glass-material-alpha-test', 'glass-alpha-test', 'value', 'glass-material', 'alphaTest'),

    conn('glass-output-base', 'glass-material', 'baseColor', 'glass-output', 'baseColor'),
    conn('glass-output-roughness', 'glass-material', 'roughness', 'glass-output', 'roughness'),
    conn('glass-output-metalness', 'glass-material', 'metalness', 'glass-output', 'metalness'),
  ],
  groups: [
    {
      id: 'glass-group-foundation',
      label: 'Glass Tint',
      nodeIds: [
        'glass-uv',
        'glass-screen-uv',
        'glass-bottom-color',
        'glass-top-color',
        'glass-left-color',
        'glass-right-color',
        'glass-ramp-vertical',
        'glass-ramp-horizontal',
        'glass-tint-balance',
        'glass-tint-mix',
      ],
      collapsed: false,
    },
    {
      id: 'glass-group-lighting',
      label: 'Highlights',
      nodeIds: [
        'glass-uv-split',
        'glass-top-low',
        'glass-top-high',
        'glass-top-highlight',
        'glass-highlight-color',
        'glass-highlight-mix',
        'glass-normal-view',
        'glass-normal-split',
        'glass-normal-abs',
        'glass-normal-invert',
        'glass-rim-low',
        'glass-rim-high',
        'glass-rim-mask',
        'glass-edge-color',
        'glass-edge-mix',
        'glass-glow-mask',
        'glass-emissive-color',
        'glass-emissive-mult',
      ],
      collapsed: false,
    },
    {
      id: 'glass-group-material',
      label: 'Material',
      nodeIds: [
        'glass-opacity-min',
        'glass-opacity-max',
        'glass-opacity-mix',
        'glass-roughness',
        'glass-metalness',
        'glass-emissive-intensity',
        'glass-clearcoat',
        'glass-clearcoat-roughness',
        'glass-alpha-test',
        'glass-material',
        'glass-output',
        'glass-geometry',
        'glass-geometry-output',
      ],
      collapsed: false,
    },
  ],
  functions: {},
}

export const APPLE_GLASS_PRESET: TSLNodeEditorPreset & { graph: TSLNodeEditorGraph } = {
  name: 'Apple Glass',
  description: 'A glossy frosted glass panel with soft highlights and translucent edge tinting',
  graph: APPLE_GLASS_GRAPH,
}

